#!/bin/sh
# Versão do Orca é atualizada apenas com: python install/version/bump_version.py major|minor|patch
# Instale: cp githooks/pre-commit .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit
exit 0
