# Generated by Django 4.2.7 on 2026-01-07 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('script_path', models.CharField(max_length=500, verbose_name='Caminho do Script')),
                ('script_type', models.CharField(choices=[('python', 'Python (.py)'), ('batch', 'Batch (.bat)'), ('powershell', 'PowerShell (.ps1)')], default='python', max_length=20, verbose_name='Tipo de Script')),
                ('retries', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('retry_delay', models.IntegerField(default=60, verbose_name='Delay entre Tentativas (segundos)')),
                ('timeout', models.IntegerField(blank=True, null=True, verbose_name='Timeout (segundos)')),
                ('schedule_type', models.CharField(choices=[('interval', 'Intervalo'), ('cron', 'Cron'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('biweekly', 'Quinzenal'), ('daily', 'Diário')], default='daily', max_length=20, verbose_name='Tipo de Agendamento')),
                ('schedule_config', models.JSONField(default=dict, verbose_name='Configuração do Agendamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='scheduler.task', verbose_name='Depende de')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scheduler.pipeline', verbose_name='Pipeline')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['pipeline', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em Execução'), ('success', 'Sucesso'), ('failed', 'Falhou'), ('retry', 'Retentativa')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Duração (segundos)')),
                ('returncode', models.IntegerField(blank=True, null=True, verbose_name='Código de Retorno')),
                ('stdout', models.TextField(blank=True, verbose_name='Saída Padrão')),
                ('stderr', models.TextField(blank=True, verbose_name='Erro')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Tentativa')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scheduler.pipeline', verbose_name='Pipeline')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scheduler.task', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Execução',
                'verbose_name_plural': 'Execuções',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='scheduler_t_created_f9e9bd_idx'), models.Index(fields=['task', '-created_at'], name='scheduler_t_task_id_2e4b29_idx'), models.Index(fields=['status'], name='scheduler_t_status_e7acfe_idx')],
            },
        ),
    ]
